#!/bin/bash

AURDIR=/home/mike/abs/

PACC='\e[0;35m'
VERS='\e[0;34m'
SNCC='\e[0;32m'
OUTC='\e[0;31m'
RELC='\e[0m'

SITE="http://aur.archlinux.org/rpc.php?type=info&arg=" 
AURSITE="http://aur.archlinux.org/packages.php?ID="

cd $AURDIR

for i in *; do
	if [ -d $i ]; then 
		if [ ! -f $i/SKIP ]; then

			AURDATA=$(wget -q "${SITE}${i}" -O -)
			AURV=$(echo "${AURDATA}" |sed -r 's#.*"[Vv]ersion":[ "]*([^",]*).*#\1#g')
			AURID=$(echo "${AURDATA}" |sed -r 's#.*"[Ii][Dd]":[ "]*([^",]*).*#\1#g')

			LOCAL=$(pacman -Q $i | awk '{print $2}')
			if [ ${AURV} = ${LOCAL} ]; then
				echo -en "Package ${PACC}$i${RELC} is ${SNCC}in sync${RELC} with AUR\n"
			else
				echo -en "Package ${PACC}$i${RELC} is ${OUTC} out of sync${RELC} with AUR\n" 
			fi
			echo -en "\tLocal:\t $VERS$LOCAL$RELC\n" 
			echo -en "\tAUR:\t $VERS$AURV$RELC\n" 
			echo -en "\tSite: ${AURSITE}${AURID}\n\n"
		fi
	fi
done

