#!/bin/bash

#sh .fehbg
urxvtd -q -o -f &
#synclient MaxSpeed=1.25
#synclient VertEdgeScroll=1
#synclient FingerHigh=40
#synclient CoastingSpeed=0

#. ~/.bashrc
 
# xsetroot -cursor_name left_ptr

if [ -f ~/.Xdefaults ]; then
  xrdb -merge ~/.Xdefaults
fi

if [ -f ~/.Xmodmap ]; then
  xmodmap  ~/.Xmodmap
fi

#myconky

xcompmgr &
#xmonad &

