#!/bin/bash

dropbox &
#sh .fehbg
# urxvtd -q -o -f &
#synclient MaxSpeed=1.25
#synclient VertEdgeScroll=1
synclient FingerHigh=40
synclient BottomEdge=4000
synclient HorizEdgeScroll=1
#synclient CoastingSpeed=0

#. ~/.bashrc

# xsetroot -cursor_name left_ptr

if [ -f ~/.Xdefaults ]; then
  xrdb -merge ~/.Xdefaults
fi

if [ -f ~/.Xmodmap ]; then
  xmodmap  ~/.Xmodmap
fi

# myconky

xset r rate 250 25

compton -b --inactive-dim 0.4
# xcompmgr -D 4 -f &
#xmonad &

# Start a D-Bus session
# Source the below file only if you do not already use the default xinitrc skeleton. 
# Otherwise you will end up with multiple dbus sessions.
source /etc/X11/xinit/xinitrc.d/30-dbus
# Start GNOME Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
# You probably need to do this too:
export GPG_AGENT_INFO SSH_AUTH_SOCK

exec awesome
