#!/bin/zsh

xrandr --output VGA1 --mode 1920x1080
if [[ $HOST == "esme" ]]
then
    xrandr --output LVDS1 --mode 1280x800 --left-of VGA1
elif [[ $HOST == "teddy" ]]
then
    xrandr --output LVDS1 --mode 1600x900 --left-of VGA1
fi


# sleep 1
# sh ~/.fehbg
# xmonad --restart
