#!/bin/zsh

if [ "$#" -lt 1 ] ; then
    BRANCH="master"
else
    BRANCH=$1
fi

echo "Branches merged into $BRANCH"

git branch -a --merged $BRANCH

echo "Branches NOT merged into $BRANCH"

git branch -a --no-merged $BRANCH
