#!/bin/zsh

if [ "$#" -lt 1 ] ; then
    BRANCH="master"
else
    BRANCH=$1
fi

echo "Branches merged into $BRANCH"

git branch --merged $BRANCH

echo "Branches NOT merged into $BRANCH"

git branch --no-merged $BRANCH
