#!/bin/zsh

#qdbus org.mpris.amarok /Player org.freedesktop.MediaPlayer.Prev
CURPOS=$(mocp -i | grep "CurrentSec" | awk '{print $2}')
TOTPOS=$(mocp -i | grep "TotalSec" | awk '{print $2}')

((EARLY=TOTPOS*5/100))

if [ "$CURPOS" -gt "$EARLY" ]
then
	mocp -f
	sleep .1
	mocp -r
else
	mocp -r
fi



