#!/bin/sh

artist=$(mpc -f %artist% | sed -n 1p)
album=$(mpc -f %album% | sed -n 1p)
title=$(mpc -f %title% | sed -n 1p)

cursongfile=$(mpc search artist "$artist" album "$album" title "$title")

mpc crop
mpc add $(mpc search artist "$artist" album "$album" | grep -v $cursongfile) 

