#!/bin/zsh

if [[ $HOST == "teddy" ]]
then
    xrandr --auto --output LVDS1 --mode 1600x900
elif [[ $HOST == "zooey" ]]
then
    xrandr --auto --output LVDS1 --mode 1280x800
fi

# sleep 1
# sh ~/.fehbg
# xmonad --restart
# killall conky
# myconky
