#!/bin/bash

xrandr --auto --output LVDS1 --mode 1600x900
sleep 1
sh ~/.fehbg
xmonad --restart
killall conky
conky -c ~/.conky/conkyrc &
conky -c ~/.conky/conky-sched &
conky -c ~/.conky/conky-event &
